- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    machine_type: n1-standard-1 # default
    image_family: ubuntu-1404-lts
    service_account_email: jenkins@devops-186919.iam.gserviceaccount.com
    credentials_file: /usr/share/jenkins/devops-0276f823ccec.json
    project_id: devops-186919

  tasks:
    - name: Launch instances
      gce:
          instance_names: dev
          machine_type: "{{ machine_type }}"
          image_family: "{{ image_family }}"
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          tags: webserver
      register: gce

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      with_items: "{{ gce.instance_data }}"

    - name: Add host to groupname
      add_host: hostname={{ item.public_ip }} groupname=new_instances
      with_items: "{{ gce.instance_data }}"

#- name: Manage new instances
 # hosts: new_instances
  #connection: ssh
  #sudo: True
  #roles:
   # - base_configuration
    #- production_server